package cloud.ambar.creditCardProduct.util;

public class Constants {
    public static String EVENT_STORE_HOST_ENV_KEY = "EVENT_STORE_HOST";
    public static String EVENT_STORE_PORT_ENV_KEY = "EVENT_STORE_PORT";
    public static String EVENT_STORE_DATABASE_NAME_ENV_KEY = "EVENT_STORE_DATABASE_NAME";
    public static String EVENT_STORE_USER_ENV_KEY = "EVENT_STORE_USER";
    public static String EVENT_STORE_PASSWORD_ENV_KEY = "EVENT_STORE_PASSWORD";
    public static String MONGODB_PROJECTION_HOST_ENV_KEY = "MONGODB_PROJECTION_HOST";
    public static String MONGODB_PROJECTION_PORT_ENV_KEY = "MONGODB_PROJECTION_PORT";
    public static String MONGODB_PROJECTION_AUTHENTICATION_DATABASE_ENV_KEY = "MONGODB_PROJECTION_AUTHENTICATION_DATABASE";
    public static String MONGODB_PROJECTION_DATABASE_NAME_ENV_KEY = "MONGODB_PROJECTION_DATABASE_NAME";
    public static String MONGODB_PROJECTION_DATABASE_USERNAME_ENV_KEY = "MONGODB_PROJECTION_DATABASE_USERNAME";
    public static String MONGODB_PROJECTION_DATABASE_PASSWORD_ENV_KEY = "MONGODB_PROJECTION_DATABASE_PASSWORD";
    public static String MONGODB_REACTION_HOST_ENV_KEY = "MONGODB_REACTION_HOST";
    public static String MONGODB_REACTION_PORT_ENV_KEY = "MONGODB_REACTION_PORT";
    public static String MONGODB_REACTION_AUTHENTICATION_DATABASE_ENV_KEY = "MONGODB_REACTION_AUTHENTICATION_DATABASE";
    public static String MONGODB_REACTION_DATABASE_NAME_ENV_KEY = "MONGODB_REACTION_DATABASE_NAME";
    public static String MONGODB_REACTION_DATABASE_USERNAME_ENV_KEY = "MONGODB_REACTION_DATABASE_USERNAME";
    public static String MONGODB_REACTION_DATABASE_PASSWORD_ENV_KEY = "MONGODB_REACTION_DATABASE_PASSWORD";
}
