data_sources:

  - id: postgres_source
    description: Events Table in Postgres
    type: postgres
    host: 172.30.0.107
    port: 5432
    username: my_es_username
    password: my_es_password
    database: my_es_database
    table: event_store
    columns:
      - id
      - event_id
      - event_name
      - aggregate_id
      - aggregate_version
      - json_payload
      - json_metadata
      - recorded_on
      - causation_id
      - correlation_id
    serialColumn: id
    partitioningColumn: correlation_id

##########################

data_destinations:

  - id: Identity_User_Authentication_Session
    description: Identity_User_Authentication_Session
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/authentication_for_all_contexts/projection/session
    username: username
    password: password
    sources:
      - postgres_source

  - id: Identity_User_PrimaryEmailVerificationCode
    description: Identity_User_PrimaryEmailVerificationCode
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/identity/user/projection/primary_email_verification_code
    username: username
    password: password
    sources:
      - postgres_source

  - id: Identity_User_TakenUsername
    description: Identity_User_TakenUsername
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/identity/user/projection/taken_username
    username: username
    password: password
    sources:
      - postgres_source

  - id: Identity_User_SentVerificationEmail_V2
    description: Identity_User_SentVerificationEmail_V2
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/identity/user/projection/sent_verification_email_v2
    username: username
    password: password
    sources:
      - postgres_source

  - id: Identity_User_UserDetailsV2
    description: Identity_User_UserDetails_V2
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/identity/user/projection/user_details_v2
    username: username
    password: password
    sources:
      - postgres_source

  - id: Identity_User_SendPrimaryEmailVerification
    description: Identity_User_SendPrimaryEmailVerification
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/identity/user/reaction/send_primary_email_verification
    username: username
    password: password
    sources:
      - postgres_source

  - id: SecuritySession_Authentication_Session
    description: SecuritySession_Authentication_Session
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/authentication_for_all_contexts/projection/session
    username: username
    password: password
    sources:
      - postgres_source

  - id: Security_Session_HashedPassword
    description: Security_Session_HashedPassword
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/security/session/projection/hashed_password
    username: username
    password: password
    sources:
      - postgres_source

  - id: Security_SessionV2_Session
    description: Security_SessionV2_Session
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/security/session/projection/session_v2
    username: username
    password: password
    sources:
      - postgres_source

  - id: Security_Session_UserWithEmail
    description: Security_Session_UserWithEmail
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/security/session/projection/user_with_email
    username: username
    password: password
    sources:
      - postgres_source

  - id: Security_Session_UserWithUsername
    description: Security_Session_UserWithUsername
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/security/session/projection/user_with_username
    username: username
    password: password
    sources:
      - postgres_source

  - id: CreditCardProduct_Product_projector
    description: CreditCardProduct_Product_ProductListItem
    type: http-push
    endpoint: http://172.30.0.106:8080/api/v1/credit_card_product/product/projection/product_list_item
    username: username
    password: password
    sources:
      - postgres_source
