services:
  backend-php:
    container_name: backend-php
    build:
      context: ./../application/backend-php
      args:
        SERVICE_NAME_IN_LOWERCASE: "all_for_local_development"
    command: [ "./run_in_local.sh" ]
    restart: always
    environment:
      EVENT_STORE_HOST: "172.30.0.107"
      EVENT_STORE_PORT: 5432
      EVENT_STORE_DATABASE_NAME: "my_es_database"
      EVENT_STORE_USER: "my_es_username"
      EVENT_STORE_PASSWORD: "my_es_password"
      EVENT_STORE_CREATE_TABLE_WITH_NAME: "event_store"
      EVENT_STORE_CREATE_REPLICATION_USER_WITH_USERNAME: "replication_username"
      EVENT_STORE_CREATE_REPLICATION_USER_WITH_PASSWORD: "replication_password"
      EVENT_STORE_CREATE_REPLICATION_PUBLICATION: "replication_publication"
      MONGODB_PROJECTION_HOST: "172.30.0.108"
      MONGODB_PROJECTION_PORT: 27017
      MONGODB_PROJECTION_AUTHENTICATION_DATABASE: "admin"
      MONGODB_PROJECTION_DATABASE_NAME: "projections"
      MONGODB_PROJECTION_DATABASE_USERNAME: "my_mongo_username"
      MONGODB_PROJECTION_DATABASE_PASSWORD: "my_mongo_password"
      MONGODB_REACTION_HOST: "172.30.0.108"
      MONGODB_REACTION_PORT: 27017
      MONGODB_REACTION_AUTHENTICATION_DATABASE: "admin"
      MONGODB_REACTION_DATABASE_NAME: "reactions"
      MONGODB_REACTION_DATABASE_USERNAME: "my_mongo_username"
      MONGODB_REACTION_DATABASE_PASSWORD: "my_mongo_password"
      SESSION_TOKENS_EXPIRE_AFTER_SECONDS: 3600
      SERVICE_NAME_IN_LOWERCASE: "all_for_local_development"
    depends_on:
      - postgres-event-store
      - mongo-projection
    expose:
      - 8080
    networks:
      development:
        ipv4_address: 172.30.0.105

  frontend:
    container_name: frontend-app
    build:
      context: ./../application/frontend-javascript/
    volumes:
      - ./../:/srv
    restart: always
    environment:
      DOMAIN_IDENTITY: "http://172.30.0.105:8080"
      DOMAIN_SECURITY: "http://172.30.0.105:8080"
      DOMAIN_CREDIT_CARD_PRODUCT: "http://172.30.0.105:8080"
    networks:
      development:
        ipv4_address: 172.30.0.106
    expose:
      - 8080
    ports:
      - "8080:8080"

  postgres-event-store:
    image: postgres:16.4
    container_name: postgres-event-store
    restart: always
    volumes:
      - ./data/postgres-event-store/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_es_username
      POSTGRES_DB: my_es_database
      POSTGRES_PASSWORD: my_es_password
    command: postgres -c wal_level=logical
    expose:
      - 5432
    networks:
      development:
        ipv4_address: 172.30.0.107

  mongo-projection:
    image: mongo:7.0.14
    container_name: mongo-projection
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_mongo_username
      MONGO_INITDB_ROOT_PASSWORD: my_mongo_password
    volumes:
      - ./data/mongo-projection/db-data:/data/db
    expose:
      - 27017
    networks:
      development:
        ipv4_address: 172.30.0.108

  ambar-emulator:
    image: ambarltd/emulator:v1.1
    container_name: ambar-emulator
    restart: always
    volumes:
      - ./ambar-config.yaml:/opt/emulator/config/config.yaml
      - ./data/ambar-emulator:/root/.local/share/ambar-emulator
    networks:
      development:
        ipv4_address: 172.30.0.109
        

networks:
    development:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.0.0/24