name: Test on PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened ]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Start Application
        working-directory: local-development
        run: ./scripts/linux/dev_start.sh
      - name: Run Tests
        working-directory: local-development/scripts/php-backend-scripts
        run: ./dev_all.sh